spring.application.name=BusTicketBooking


server.port=8081

spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=BusTicketBooking;encrypt=false;trustServerCertificate=true
spring.datasource.username=your db root name
spring.datasource.password=your db root-password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Google Gemini AI
# ==========================

spring.ai.google.genai.api-key=AqUa**********************

spring.ai.google.genai.chat.options.model=gemini-flash-latest